### ISSUE TITLE
Proposal for action behind the undo delete btn

### ISSUE THREAD

**Issue by RonaldoMine** [ln-dev7/delete-interaction-1#1]
Only after you confirm the deletion does it work, but it seems that when trying to undo, nothing happens. This might be because no undo action has been implemented. Here is my proposal to add at the end of the **src/main.js** file.

`
noBtn.addEventListener("click", () => {
  gsap.to(".container", {
    duration: primaryDuration,
    opacity: 0,
  });
  gsap.to(".top", {
    duration: primaryDuration,
    rotate: -40,
  });
  gsap.to(deleteBtn, {
    y: 2,
    onComplete: () => {
      gsap.to(deleteBtn, {
        width: "150px",
        height: "50px",
        borderRadius: "8px",
      });
      gsap.to(".delete span", {
        duration: primaryDuration,
        opacity: 1,
      });
      gsap.to(".top", {
        duration: primaryDuration,
        opacity: 0,
        rotate: 0,
      });
      deleteBtn.disabled = false;
    },
  });
});
`

Demo : 

https://github.com/ln-dev7/delete-interaction-1/assets/38324251/f7aefe47-e02e-45dc-bb00-ca929a1d3897

**Comment by ln-dev7** [comment]
Thanks you ! 
You can directly make a PR

**Comment by RonaldoMine** [comment]
it's done @ln-dev7 you can check : https://github.com/ln-dev7/delete-interaction-1/pull/2
